version: "3.9"

#Definición de los servicios web (Flask) y nginx (proxy inverso)
services:
  web:
    build: .
    # ports:
    #  - "5001:5000"  # si quieres exponer el puerto del contenedor

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    depends_on:
      - web
